site:
    title: cwen's blog
    introduce: 沉稳，不乏可爱
    limit: 10
    theme: "themes/default"
    url: http://www.cwen.pw
    comment: www-cwen-pw
    github: "https://github.com/cwen-coder"
    facebook:
    twitter:
serve:
    addr: "localhost:3000"

publish:
    cmd: |
        git add -A
        git commit -m "update"
        git push origin

